version: "3.7"
services:
  web:
    build: ./web/.
    ports:
      - "8000:5000"
    volumes:
      - ./web/.:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB
    ports:
      - '5432:5432'
    # volumes:
      # - ./db:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  jupyter:
    image: jupyter/scipy-notebook
    ports: 
      - "10000:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes